### ISSUE TITLE
Remove the use of aries_vcx_core/wallet/indy/internal from api_global

### ISSUE THREAD

**Issue by xprazak2** [hyperledger/aries-vcx#1115]
The name `internal` suggests the module is not for public use and yet it is used by `api_global`. Find a way how to refactor and possibly remove it.

**Comment by PanGan21** [comment]
Hi, I was looking at this issue. What is the profile wallet that is supposed to replace the internal module according to the comments?

**Comment by PanGan21** [comment]
Thanks for letting me know! It seems that no work is required for this issue then :)

**Comment by Patrik-Stas** [comment]
@xprazak2 I guess we can close this now given we've dropped support for `libvcx` right?

**Comment by xprazak2** [comment]
Yes.
