### ISSUE TITLE
Publish image CI action has undeclared dependency. 

### ISSUE THREAD

**Issue by nain-F49FF806** [hyperledger/aries-vcx#1140]
`.github/actions/publish-image` uses environment variable `$URL_DOCKER_REGISTRY` to decide which root registry to push to.   
If this is not set globally, or at some step before the action's invocation, it will fail to publish. 

This can be surprising, as the necessity of this environment variable is not mentioned anywhere. 

It would be better to have this as an input to the action, with a default value: 'ghcr.io'.

**Comment by PanGan21** [comment]
Hi! Could I pick it up? :)

**Comment by nain-F49FF806** [comment]
@PanGan21 Sure, go for it!

**Comment by nain-F49FF806** [comment]
@Patrik-Stas Could you like to take a look at the issue and opine if PanGan21 should start attempting a fix?

**Comment by PanGan21** [comment]
Hey @nain-F49FF806  I did some work already in #1142 
Would be nice to allow the pipelines to run in order to check if my fix is working :)
