### ISSUE TITLE
Integration tests with AcaPy as part of CI

### ISSUE THREAD

**Issue by Patrik-Stas** [hyperledger/aries-vcx#157]
- Acapy is fairly mainstream choice for open source institutional agent
- aries-framework-rs provides interfaces for mobile
- there's good chance and aries-framework-rs based app would interact with acapy
- To make sure we are not in a buble, it would be great to have integration tests with acapy as part of Github Actions CI

- Attaching `help-wanted` label, we as Absa don't plan to work on this in upcoming future, but this issue is here as invitation for others to contribute

**Comment by airoasis** [comment]
We may use https://github.com/hyperledger/aries-agent-test-harness for integration testing. It has the VCX in their backchannels :)

**Comment by khujin1** [comment]
Hi Patrik. As you may know we are using both aca-py and vcx.
So I created new repository for aca-py and vcx interoperability demo test.
https://github.com/sktston/acapy-vcx-demo

It's not Github Actions CI but I will consider it after our production development.

**Comment by Patrik-Stas** [comment]
@khujin1 @airoasis you guys rock! Very well done

**Comment by Patrik-Stas** [comment]
Closing this as per work being done on aries-agent-test-harness https://github.com/hyperledger/aries-agent-test-harness/pull/243
