### ISSUE TITLE
Port vcx-agency-node to Rust

### ISSUE THREAD

**Issue by Patrik-Stas** [hyperledger/aries-vcx#197]
Currently the only open-source `aries-vcx` agency is [vcx-agency-node](https://github.com/AbsaOSS/vcxagencynode/) written in Node. This brings extra maintenance overhead and duplication:
- the message types are defined on 2 places (aries-vcx and in Node agency)
- Node agency has it's own implementation of agency-client written for purpose of integration testing
- Node agency is dependency on IndySDK and crippled by performance issues caused by blocking storage API in IndySDK - it would be good start to replace IndySDK in agency by using aries-askar. We could learn something before we attempt to migrate `aries-vcx` away from `libindy`. It's also more accessible to experiment with aries-askar and other aries/indy crates from Rust, as in case of Node, we would have to write Node FFI wrappers.
- `aries-vcx` as a whole and mediator agency go hand in hand and it would make sense to test them in one CI.

**Comment by kukgini** [comment]
In my humble opinion, by complying with RFC 0211, it should be considered to reduce the scope of development by enabling aca-py to be used as a mediator.

**Comment by Patrik-Stas** [comment]
Closing this as we no longer to plan to do this work. Community effort to write agency client compliant with mediation aries RFC will be appreciated though!
