### ISSUE TITLE
Fix pool dockerfile

### ISSUE THREAD

**Issue by mirgee** [hyperledger/aries-vcx#218]
During the build of the pool docker image, pip installation fails with the following warnings:
```
#6 [3/11] RUN pip3 install -U 	pip==9.0.3 	setuptools
#6 1.341 Collecting pip==9.0.3
#6 1.643   Downloading https://files.pythonhosted.org/packages/ac/95/a05b56bb975efa78d3557efa36acaf9cf5d2fd0ee0062060493687432e03/pip-9.0.3-py2.py3-none-any.whl (1.4MB)
#6 2.354 Collecting setuptools
#6 2.673   Downloading https://files.pythonhosted.org/packages/6d/38/c21ef5034684ffc0412deefbb07d66678332290c14bb5269c85145fbd55e/setuptools-50.3.2-py3-none-any.whl (785kB)
#6 2.846 Installing collected packages: pip, setuptools
#6 2.846   Found existing installation: pip 8.1.1
#6 2.849     Not uninstalling pip at /usr/lib/python3/dist-packages, outside environment /usr
#6 3.612   Found existing installation: setuptools 20.7.0
#6 3.614     Not uninstalling setuptools at /usr/lib/python3/dist-packages, outside environment /usr
#6 3.987 Successfully installed pip-9.0.3 setuptools-50.3.2
#6 4.143 You are using pip version 9.0.3, however version 20.2.4 is available.
#6 4.143 You should consider upgrading via the 'pip install --upgrade pip' command.
```
Related to these (perhaps causally) may be the following error, which fails the build:
```
#10 [7/11] RUN apt-get update -y && apt-get install -y         python3-pyzmq...
#10 0.597 Get:1 https://repo.sovrin.org/deb xenial InRelease [28.4 kB]
#10 0.610 Hit:2 http://security.ubuntu.com/ubuntu xenial-security InRelease
#10 0.612 Hit:3 http://archive.ubuntu.com/ubuntu xenial InRelease
#10 0.691 Hit:4 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
#10 0.697 Get:5 https://repo.sovrin.org/deb xenial/master amd64 Packages [345 kB]
#10 0.771 Hit:6 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
#10 1.037 Fetched 373 kB in 0s (535 kB/s)
#10 1.037 Reading package lists...
#10 2.041 Reading package lists...
#10 3.065 Building dependency tree...
#10 3.197 Reading state information...
#10 3.242 Some packages could not be installed. This may mean that you have
#10 3.242 requested an impossible situation or if you are using the unstable
#10 3.242 distribution that some required packages have not yet been created
#10 3.242 or been moved out of Incoming.
#10 3.242 The following information may help to resolve the situation:
#10 3.242 
#10 3.242 The following packages have unmet dependencies:
#10 3.292  indy-plenum : Depends: python3-orderedset (= 2.0) but 2.0.3 is to be installed
#10 3.292                Depends: python3-psutil (= 5.4.3) but 5.6.6 is to be installed
#10 3.292                Depends: python3-psutil (= 5.4.3) but 5.6.6 is to be installed
#10 3.292                Depends: python3-pympler (= 0.5) but 0.8 is to be installed
#10 3.300 E: Unable to correct problems, you have held broken packages.
```

This may be related to the [recent changes](https://pip.pypa.io/en/stable/user_guide/#changes-to-the-pip-dependency-resolver-in-20-2-2020) in the way pip resolves dependencies, or the new version of setuptools.

Temporarily, this issue was resolved by [fetching](https://github.com/hyperledger/aries-vcx/pull/217) a prebuilt pool image uploaded to GitHub Container Registry.

**Comment by tarun27in** [comment]
I can acknowledge that while going through Indy's getting started guide. I see the same error when I do

> docker-compose up

**Comment by Sirius-social** [comment]
I see same problem with https://github.com/hyperledger/indy-sdk/blob/master/ci/indy-pool.dockerfile

**Comment by GuilhermeMenezes** [comment]
Hello, how are you?
I have the lastest version from master, but i still get the same bug when trying to build the pool like it says in the Indy's started guide:
...
Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:3 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu xenial-security InRelease
Get:5 https://repo.sovrin.org/deb xenial InRelease [28.4 kB]
Get:6 https://repo.sovrin.org/deb xenial/master amd64 Packages [345 kB]
Fetched 373 kB in 1s (209 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 indy-plenum : Depends: python3-orderedset (= 2.0) but 2.0.3 is to be installed
               Depends: python3-psutil (= 5.4.3) but 5.6.6 is to be installed
               Depends: python3-psutil (= 5.4.3) but 5.6.6 is to be installed
               Depends: python3-pympler (= 0.5) but 0.8 is to be installed
E: Unable to correct problems, you have held broken packages.

Any ideas on what's wrong?

**Comment by ThomasBronsveld** [comment]
Hello, I just worked through the readme and pulled the repo from the master. 

I got the exact same issues as GuilhermeMenezes with the current master.

I am running an ubuntu 20.04 machine if that helps in some regard.
