### ISSUE TITLE
Reorganize code inside `handlers` module

### ISSUE THREAD

**Issue by Patrik-Stas** [hyperledger/aries-vcx#337]
`aries_vcx` is currently organized primarily per protocol, eg. `src/handlers/connection`, `src/handlers/issuance` and within each protocol is contained both logic of both `aries_vcx` and Aries FSM (as referred to in diagram https://github.com/hyperledger/aries-vcx/blob/main/docs/architecture/ariesvcx_architecture_now_180821.png )

The code should be reorganized as follows:
```
- src 
    - aries 
       - messages/..
       - utils/..
       - fsm
           - connection
               - invitee
                   - states/..
                   - state_machine.rs
               - inviter/..
           - issuance
               - holder/..
               - issuer/..
           - presentation/..
    - vcx
       - connection.rs
       - issuer.rs
       - holder.rs
       - prover.rs
       - verifier.rs
```

so that the business of `aries_vcx` is contained in module `vcx` and everything aries related, which should ideally have no dependency on ledger or credential library, shall be contained in module `aries`.

**Comment by mirgee** [comment]
Addressed by #436 .
