### ISSUE TITLE
Add support for DID in OOB service field

### ISSUE THREAD

**Issue by Patrik-Stas** [hyperledger/aries-vcx#424]
OOB message looks as described here https://github.com/hyperledger/aries-rfcs/blob/main/features/0434-outofband/README.md#messages

And particularly about field `services`

> services - an array of union types that the receiver uses when responding to the message. Each item is either a DIDComm service object (as per RFC0067) or a DID (as per Decentralized Identifiers v1.0). Additional details below.

We currently implement method for appending service object, but not DID.

**Comment by mirgee** [comment]
Fixed by #428.
