### ISSUE TITLE
hello how to contribute ?

### ISSUE THREAD

**Issue by marcpar** [hyperledger/aries-vcx#501]
Hi Im a rust developer i would like to contribute on this project

thanks

**Comment by mirgee** [comment]
Hello @marcpar and welcome! If you are interested in contributing, we have a number of issues labeled as "good first issue" (and more are coming in time). The descriptions are not as detailed as one might wish, but they should be good enough for you to know if you are interested, in which case we are ready to answer any questions you might have on our [discord channel](https://discord.com/channels/905194001349627914/955480822675308604).

Moreover, if you are interested in working in Rust on SSI full-time, Absa, currently the main sponsor of this project, is hiring:
https://www.hyperledger.org/job/absa-bank-czechia-or-eu-region-144-backend-software-engineer-rust
https://www.hyperledger.org/job/absa-bank-czechia-or-eu-region-144-fullstack-software-engineer-javascript-typescript
https://www.hyperledger.org/job/absa-bank-czechia-or-eu-region-144-backend-software-engineer-node-js
https://www.hyperledger.org/job/absa-bank-czechia-or-eu-region-144-frontend-software-engineer-react
https://www.hyperledger.org/job/absa-bank-czechia-or-eu-region-144-mobile-software-engineer-react-native
