### ISSUE TITLE
Adhere to did:sov method spec

### ISSUE THREAD

**Issue by Patrik-Stas** [hyperledger/aries-vcx#609]
Currently, aries-vcx expects DIDs on Indy ledger may contain `attribute` in following format to express their contact endpoint, recipient and routing keys
```
{
    "service": {
        "id": "did:example:123456789abcdefghi;indy",
        "priority": 0,
        "recipientKeys": [
            "A5dc4WEXzE8S6ESKMFiimGMhQeyn7CBcu8FrnJxR2c7Y"
        ],
        "routingKeys": [
            "5Mt5KCoTBdYVne9JxufF7QRT5xvWCPdBG2ZkBQoWiQ8o",
            "Hezce2UWMZ3wUhVkh2LfKSs8nDzWwzs2Win7EzNN3YaR"
        ],
        "serviceEndpoint": "https://ea.uat.absa.africa/agency/msg",
        "type": "IndyAgent"
    }
}
```
However this is out of sync with https://sovrin-foundation.github.io/sovrin/spec/did-method-spec-template.html and arguably it's not yet quite clear from the spec how `recipientKeys` should be written on the ledger. However, as per spec, the actual format we should write and read looks [like this](https://sovrin-foundation.github.io/sovrin/spec/did-method-spec-template.html#crud-operation-definitions):
```
{
  "endpoint": "https://example.com",
  "types": [ "endpoint", "did-communication", "DIDComm" ],
  "routingKeys": [ "did:key12345", "did:key12345" ]
}
```

Getting this right is important interop property when dealing with OOB invitations / conneciton protocol invitations, which do not specify entire `service` object, but only specify a did for the recipient to resolve.

**Comment by swcurran** [comment]
@dbluhm and @TimoGlastra -- wanted to make sure you saw this and provided input on what has been done in ACA-Py and AFJ on this to make sure we get interoperability right amongst the Frameworks. Would it make sense to point to the implementations in your respective frameworks (or perhaps unit tests?) to make sure we nail this?

**Comment by Patrik-Stas** [comment]
@swcurran thanks for initiative Stephen!

In the meantime, as guijd3p on discord offered to work on this, basically some implementation instructons:

### 1. Writing
Adjust 
```
pub async fn add_service(wallet_handle: WalletHandle, pool_handle: PoolHandle, did: &str, service: &AriesService) -> VcxResult<String> {
```
so it can write on ledger `service` did attribute in either the our current (incorrect) format, or the new, correct one (per rfc / inspiration from afj/acapy)

### 2. Reading
Adjust
```
pub async fn get_service(pool_handle: PoolHandle, did: &Did) -> VcxResult<AriesService> {
```
so it can construct `AriesService` from the new format, if that fails, fallback trying to assuming the current (inccorect) format. If that fails too, return error.

Importantly I'd like to see the PR coming with unit test to verify that both old and new format can be processed by `get_service`

**Comment by TimoGlastra** [comment]
As indy dids can currently only contain a single key (the verkey), that is always the recipient key at the moment. So to translate it to a valid service, you can extract the verkey as the recipientKey. All other values can be extracted from the ATTRIB as described in the did sov spec

**Comment by guijd3p** [comment]
@Patrik-Stas 
Hello I was analyzing this feature.

And I would like to ask some questions about this add_service method
https://github.com/hyperledger/aries-vcx/blob/main/aries_vcx/src/indy/ledger/transactions.rs#L400


I performed a review of the implementation in the afj project https://github.com/hyperledger/aries-framework-javascript/blob/main/packages/core/src/modules/dids/methods/sov/SovDidRegistrar.ts

  In this case every time it's a public-invite they generate a prefix "did.sov" with did, it doesn't persist the did with that suffix because it would give an error when saving in the ledger. It appears only in the invite printout.

And also analyzed the generation of public-inivit by acapay https://github.com/hyperledger/aries-cloudagent-python/blob/main/aries_cloudagent/protocols/out_of_band/v1_0/manager.py#L231

In both cases, they are only treated when receiving the public-invite and when returning the invite construction.


So I see that we don't really need to save the did with the prefix did:sov, just know how to handle it in the construction of the message and in the reading.


So whenever the two will generate a public-invite they have this structure.


{
    "@type": "https://didcomm.org/out-of-band/1.0/invitation",
    "@id": "a24b7cd3-3029-4403-90fe-3ea4b1a999ec",
    "label": "faber.agent",
    "services": [
      "did:sov:Bp3pqJY8Yttav2JNcv6NxV" ],
    "handshake_protocols": [
      "https://didcomm.org/didexchange/1.0",
      "https://didcomm.org/connections/1.0" ]
}

Could we always generate with the prefix did:sov?
Another issue is the creation of the invite message not published with the following structure.

   "services": [
      {
        "id": "#inline",
        "type": "did-communication",
        "recipientKeys": [
          "did:key:z6MkkUWPbPBZjVVespRojrsP73y9nVgyMzvJg4nebEZii3uw" ],
        "serviceEndpoint": "http://127.0.0.1/faber" }
    ],

is services direct this reading of did:key will be handled in this task?

**Comment by Patrik-Stas** [comment]
Hi @TimoGlastra thanks for hopping in here! So with VCX, as you can see in the example of what we currently write/read on ledger from VCX, there's 2 differences:
1. formatting, that'll be easy fix
2. we do not assume DID's verkey === recipient key; we write value of recipient key on the ledger explicitly, as part of the service object

To find common ground with other frameworks, I think we can take this in few steps @guijd3p 
#### Stage 1
Main goal we want to focus first is to enable interop for `[mobile VCX] ----> [arbitrary institution agent]`. That is pretty low hanging fruit, as other than formatting, we'll have to resolve DID's verkey and use it as recipient key in aries context.

Implementation: 
- No modification to the format of ATTRIB written to the ledger by VCX
- Update our implementation of resolve a DID into AriesService
```
pub async fn get_service(pool_handle: PoolHandle, did: &Did) -> VcxResult<AriesService> {
```
such that we
- first follow the sov spec, eg we assume following format (so this would be actually 2 calls, 1 to get ATTRIB, 1 to resolve the DID and use it as recipientKey)
```
{ "endpoint": { "endpoint": "https://example.com", "types": [ "endpoint", "did-communication", "DIDComm" ], "routingKeys": [ "did:key12345", "did:key12345" ]} }
```
- if that fails, fallback to retry assuming the legacy format (the current one), eg:
```
{"service":{"id":"did:example:123456789abcdefghi;indy","priority":0,"recipientKeys":["A5dc4WEXzE8S6ESKMFiimGMhQeyn7CBcu8FrnJxR2c7Y"],"routingKeys":["5Mt5KCoTBdYVne9JxufF7QRT5xvWCPdBG2ZkBQoWiQ8o","Hezce2UWMZ3wUhVkh2LfKSs8nDzWwzs2Win7EzNN3YaR"],"serviceEndpoint":"https://example.com","type":"IndyAgent"}}
```
 
#### Stage 1.5
Next we would focus on improving `[a mobile framework] ----> [institution VCX]` interop. 

- Change what VCX writes on the ledger, instead of 
```
{"service":{"id":"did:example:123456789abcdefghi;indy","priority":0,"recipientKeys":["A5dc4WEXzE8S6ESKMFiimGMhQeyn7CBcu8FrnJxR2c7Y"],"routingKeys":["5Mt5KCoTBdYVne9JxufF7QRT5xvWCPdBG2ZkBQoWiQ8o","Hezce2UWMZ3wUhVkh2LfKSs8nDzWwzs2Win7EzNN3YaR"],"serviceEndpoint":"https://example.com","type":"IndyAgent"}}
```
we will write 
```
{ "endpoint" :{ "endpoint": "https://example.com", "types": [ "endpoint", "did-communication", "DIDComm" ], "routingKeys": ["5Mt5KCoTBdYVne9JxufF7QRT5xvWCPdBG2ZkBQoWiQ8o","Hezce2UWMZ3wUhVkh2LfKSs8nDzWwzs2Win7EzNN3YaR"], "recipientKeys":["A5dc4WEXzE8S6ESKMFiimGMhQeyn7CBcu8FrnJxR2c7Y"]}}
```
to at least fix formatting. This would be still miss-alligned as we would include `recipientKeys`, which only `aries-vcx` clients would understand.

#### Stage 2
Unless `did:sov` spec would be tweaked to include option specifying `recipientKeys`, we would have to drop it. Dropping it shouldn't be an issue after we implement https://github.com/hyperledger/aries-vcx/issues/618

**Comment by Patrik-Stas** [comment]
@swcurran @TimoGlastra  as per what I mention in "Stage 2", previous comment - what's your's guys take on tweaking `did:sov` spec to enable specifying `recipientKeys` in ATTRIB similarly to `routingKeys`, instead of assuming that `recipinetKey === DID's verkey`?

**Comment by Patrik-Stas** [comment]
@swcurran 
I see that the latest revision of `did:sov` spec actually added handling specification custom recipient keys https://sovrin-foundation.github.io/sovrin/spec/did-method-spec-template.html#crud-operation-definitions it seems that
