### ISSUE TITLE
Return presentation status enums instead of u32 code

### ISSUE THREAD

**Issue by Patrik-Stas** [hyperledger/aries-vcx#617]
- Method
```
pub fn get_presentation_status(&self) -> u32 {
```
returns u32 numbers which represent status codes of presentation status. On `aries-vcx`, we should work with enumerations. Mapping to u32 should be defined on `libvcx` level. 

- This also means that number of integration tests is working is asserting enums by converting the to `u32`, like 
```
assert_eq!(
            verifier.get_presentation_status(),
            ProofStateType::ProofValidated as u32
        );
```
so this should instead look like 
```
assert_eq!(
            verifier.get_presentation_status(),
            ProofStateType::ProofValidated
        );
```

- Make sure to maintain the mapping for backwards compatibility

**Comment by BulkBeing** [comment]
@Patrik-Stas May I work on this ?
