### ISSUE TITLE
Process prefixed DIDs in aries messages

### ISSUE THREAD

**Issue by Patrik-Stas** [hyperledger/aries-vcx#627]
Currently aries-vcx assumes `did` in connection protocol public invitations, out of band protocol invitations, do not contain `did:sov` prefix. Equally, `aries-vcx` does generate aries messages which do not contain the prefix.

Useful context from @guijd3p in this post analyzing how this is treated by other implementations
https://github.com/hyperledger/aries-vcx/issues/609#issuecomment-1292698710

**Comment by Patrik-Stas** [comment]
@guijd3p do I understand your proposal correct, to simply remap `did:sov:abc12346` to -> `abc12346` when processing public/oob invitations, and keep the inner layers of code intact? 

 Sounds fair to me. 
 Thoughts @mirgee ?
 
 
 We could add probably similar support for `did:peer`, but that could be treated as separate issue.

**Comment by guijd3p** [comment]
I was having problems with my ledger, but yes it saves when an invite public is created
