### ISSUE TITLE
AATH: Allow exposing cloud agency publicly (via ngrok)

### ISSUE THREAD

**Issue by mirgee** [hyperledger/aries-vcx#636]
So far, two issues have been discovered throughout mobile wallet interoperability testing against AriesVCX AATH backchannel:

* Missing `@type` property in the invitation generated by AriesVCX means the mobile backchannel is unaware of the received message type, and
* agency not being exposed publicly (e.g. via ngrok) means that the backchannels are not able to communicate at all.

These two issues need to be resolved in order to continue interoperability testing between AriesVCX and mobile wallet backchannels.

https://github.com/hyperledger/aries-agent-test-harness/issues/560

**Comment by Patrik-Stas** [comment]
not relevant anymore, agency is not used anymore
