### ISSUE TITLE
Remove PublicAgent and its usage

### ISSUE THREAD

**Issue by Patrik-Stas** [hyperledger/aries-vcx#679]
- Remove `PublicAgent` structure and its usage in tests

@pomfar @kukgini @gmulhearn-anonyome @guijd3p @PaulRps is anyone of you using `PublicAgent` structure?

**Comment by PaulRps** [comment]
nope.

**Comment by gmulhearn-anonyome** [comment]
nope

**Comment by pomfar** [comment]
nope

**Comment by Patrik-Stas** [comment]
Thank you guys for feedback. We'll be removing this soon
