### ISSUE TITLE
Support did:key (Aries RFC #0360)

### ISSUE THREAD

**Issue by Patrik-Stas** [hyperledger/aries-vcx#689]
- Implement support for `did:key` https://github.com/hyperledger/aries-rfcs/tree/main/features/0360-use-did-key
  - Implement conversion code which can transform `ed25519` did:key formatted key to "naked" key which can be used with current underlying codebase 
  - Implement conversion code to convert current "naked" ed25519 key to valid `did:key`. 
  - Implement tests covering these conversions
  - When processing aries messages containing public keys, detect whether the key is "naked" or did:key. If it is did:key, convert it to naked key
  - For now, only allow did:keys which are `ed25519-pub` keys

**Comment by Patrik-Stas** [comment]
@guijd3p any thoughts? If you are going to start working on this, please assign the task to yourself

**Comment by gmulhearn** [comment]
@Patrik-Stas left a comment on the PR, but just for awareness - this ticket may not be 100% complete. Other areas may require conversion from did:key to naked, e.g. 'routing keys' and maybe other places too. I believe the recent PR just focused on just transforming the 'recipient keys'. Should be easy to implement with the new transformer function tho!
