### ISSUE TITLE
Synchronize state machine approach

### ISSUE THREAD

**Issue by Patrik-Stas** [hyperledger/aries-vcx#696]
State machines in
- `protocols/issuance`
- `protocols/proof_presentation`
are using old approach of triggering state transitions. These state machines provide single function interface, a function called `step` or `handle_message` which allows for passing "Action" enum variants. For example, in case of issuance it is enum `CredentialIssuanceAction`. This enum defines several variants, each representing a "request" or "command" to run certain state transition. Often, these variants are parametrized, for example in case of `CredentialIssuanceAction`, there is `CredentialProposalSend(CredentialProposalData)` and similar. This is makes it more difficult to pass more advanced data structures to the state machine, such as closures. 

The `protocols/connection` has already been refactored long time ago to eliminate this "action" struct approach. Instead, each state transition (a variant in the "action" approach) is mapped to a function with whatever arguments that transition requires, including closures (currently typically a closure to send message to counter-party). The same approach should be applied to the fore-mentioned 
- `protocols/issuance`
- `protocols/proof_presentation`
state machines. 

These modifications will "trickle up" with some consequences to upper `src/handlers` layer which will need to be adjusted respectively, likely moving bit of orchestration logic there.

**Comment by bobozaur** [comment]
This will get covered in the upcoming state machines refactor to the typestate pattern.

**Comment by Patrik-Stas** [comment]
Correcto, closing this
