### ISSUE TITLE
Move out `post_message` to `shared_vcx`

### ISSUE THREAD

**Issue by Patrik-Stas** [hyperledger/aries-vcx#772]
### Good first issue! You can learn bit of a Rust and the codebase by doing this

Task:
- Function in `agency_client/src/httpclient.rs`  are currently being used by `aries_vcx` - but we strive for `aries_vcx` to have no dependency of `agency_client`
- Move the code to `shared_vcx` instead 

What you learn:
- rust modules
- rust imports
- glance into the codebase

**Comment by Parikalp-Bhardwaj** [comment]
Hey @Patrik-Stas then this issue need to be removed

**Comment by Patrik-Stas** [comment]
Hi @Parikalp-Bhardwaj we keep issues open until they are fully addressed, eg. the code is merged. 

Again I am sorry for confusion, it would be a lot clearer if Andy could had been assigned on the issue, unfortunately it seems not to be possible. Perhaps per some Hyperledger org. settings, I'll see if something can be done about that.
