### ISSUE TITLE
Cleanup `aries_vcx/src/utils/constants.rs`

### ISSUE THREAD

**Issue by Patrik-Stas** [hyperledger/aries-vcx#773]
#### Good first issue! You can learn bit of a Rust and the codebase by doing this

Task:
- Remove unused constants 
- Cherry on top: reformat json constants from single-line to multi-line JSONs to make them easier to read
- Divide into multiple files 

Learning points:
- rust imports
- rust "features" - you will encounter that some constants are only being used when compiled with certain feature flag
- refactoring rust code - you will see that IDEs tends to be pretty smart with refactoring Rust code and it's possible to move constants to other file and having (most) imports fixed by IDE

**Comment by ggold7046** [comment]
Hi @Patrik-Stas , I would like to work on this issue. Though I'm new to Aries.
