### ISSUE TITLE
Write unit tests for `Schema`

### ISSUE THREAD

**Issue by Patrik-Stas** [hyperledger/aries-vcx#775]
File `credential_schema.rs` contains `Schema` struct and implementation

Task:
- Level easy: Write unit tests for functions: `to_string_versioned`, `from_string_versioned`, `get_schema_id`,
- Level medium: Write unit tests for function `create`, `create_from_ledger_json`, `publish`

Learning:
- Level easy: Testing in rust
- Level medium: 
  - Dealing with Traits (some methods call in the method implementations are behind traits)
  - Mocking - you might have to mock trait implementation to avoid actually calling ledger / wallet

**Comment by masterismail** [comment]
Hi, I'd like to contribute to the resolution. Does anyone have updates on the status of this issue or suggestions on how to approach it? Specifically, could someone provide more details about the error message that's being displayed? Any information would be greatly appreciated. Thanks!

**Comment by Patrik-Stas** [comment]
Hi @masterismail apologies, I've missed your comment. It seems that the issue has now been picked up by @nachiketkanore 
in https://github.com/hyperledger/aries-vcx/pull/808
