### ISSUE TITLE
Android: vcxOpenMainPool path

### ISSUE THREAD

**Issue by stephanhalbritter** [hyperledger/aries-vcx#779]
Hello,

using the Android libvcx wrapper, I ran into the following problem. 

When running `VcxApi.vcxOpenMainPool(poolConfig)`, it creates a folder `$HOME/.indy_client/pool/`. This is a problem on Android, as this location is world-accessible. It would also need special permissions given by the user to write there and would not be deleted when uninstalling the app.

In the walletConfig for `VcxApi.vcxInitThreadpool(walletConfig)` it's possible to set `storage_config -> path` to a path inside the app sandbox (e.g. with `context.filesDir.absolutePath`), skipping all the problems described above.

[Edit: to clarify, `storage_config -> path` does *not* skip the problem for `vcxOpenMainPool`. But without that parameter a similar problem would exist for `vcxInitThreadpool`]

I would be very glad if someone could give me a hint how to solve this.

**Comment by Patrik-Stas** [comment]
Hi @stephanhalbritter 

I am a bit confused when you refer to `vcxInitThreadpool` - but given the overall context, I suppose that was a typo and you meant to write `openMainWallet`  instead of `vcxInitThreadpool `?

So if I understand it right, you are suggesting that config for `vcxOpenMainPool` would accept optional attribute to specify the location of pool directory it creates? Sounds good to me!

**Comment by Patrik-Stas** [comment]
Hi Stephan, I believe you are bit mistaken here as you hold onto `vcxInitThreadpool ` as example but that function does not create any files, nor it accepts path in its config argument.

Nevertheless I think we are on the same page. We have currently other higher priority areas we focus on, but this would be great first contribution. I believe it shouldn't be challenging to implement either. Would you guys give it a shot?

Before you start changing signatures and digging into code, I encourage you to investigate where are these files being actually created. It seem to be happening in `libvdrtools/indy_utils/src/environment.rs` - see methods
```
wallet_home_path
pool_home_path
pool_path
```
There's also some special handling for android - see method `android_indy_client_dir_path` ;-) Take a look, it seems like no extra functionality needs to be implemented to get your problem solved
