### ISSUE TITLE
Remove IO between the parties in protocol integration tests

### ISSUE THREAD

**Issue by Patrik-Stas** [hyperledger/aries-vcx#786]
Rewrite integration tests such that tests focused on non-connection protocols do not exchange messages via didcomm, instead juggle the messages between 2 instance of state machines - simply assume a trusted communication channel exist.

Eg where previously we would have code
```
prover.build_presentation()
send_presentation(prover, connection_prover_to_verifier) // generate message, send it over didcomm connection
try_verify_presentation(verifier, connection_verifier_to_prover) // lookup messages in agency, pick presentation req., try to use it to drive protocol
```
while the code sample looks fairly simply here, the illustrated methods would typically do bunch of stuff behind the scenes as indicated by comment.

So instead, we should do:
```
prover.build_presentation()
let msg = prover.get_presentation_msg();
verifier.process_presentation(msg)
```
and not concern ourselves with the message delivery at all. Just pass the message around the memory for test purpose.

### Note:
This also ties with refactoring around state machines which has been discussed but yet not formalized as Github issue - state machines themselves should not be concerned with sending any data in the first place. That means we need to eliminate states like `<MsgType>Sent` (for example `PresentationRequestSentState` in proof verifier)

**Comment by styvane** [comment]
I want to work on this one.
