### ISSUE TITLE
InviterConnection::handle_request (or equivilant) should take new pairwise as a parameter

### ISSUE THREAD

**Issue by gmulhearn-anonyome** [hyperledger/aries-vcx#791]
`Connection::handle_request` currently takes `new_service_endpoint` and `new_routing_keys` parameters which are passed to the invitee in the response message to inform them of the new DIDComm connection route. However this method does **not** take a `new_pairwise_info` parameter, instead it is generated on the fly within the method;

```
        let new_pairwise_info = PairwiseInfo::create(wallet).await?;
```

IMO, pairwise info should be passed into this method, as it is entirely possible that the consumer needs to have access to their `new_pairwise_info` BEFORE they send/generate a connection response message (e.g. they need to register it with their mediation service).

I know this typestate impl is going to be modified a bit in the near future, so I'm just making this issue such that it can hopefully be address as part of the re-working. (if you guys agree it's a problem)

Thanks!

**Comment by gmulhearn** [comment]
closing as mostly deprecated
