### ISSUE TITLE
Update `time` crate dependency to version 0.3.x

### ISSUE THREAD

**Issue by Patrik-Stas** [hyperledger/aries-vcx#795]
Info:
- We are using time `0.1.x`
- Latest version is `0.3.x`
- There's breaking changes between `0.1.x` and `0.2.x` (attempt for automatic update by dependabot fails https://github.com/hyperledger/aries-vcx/pull/792)
- Likely breaking changes between `0.2.x` and 0.3.x` as well

Task:
- Update `time` crate to latest version

**Comment by Parikalp-Bhardwaj** [comment]
Hey @Patrik-Stas Updated the time dependency to version 0.3.20

**Comment by Patrik-Stas** [comment]
Picked up by @swaptr in https://github.com/hyperledger/aries-vcx/pull/800
