### ISSUE TITLE
Typed interfaces/traits for BaseWallet

### ISSUE THREAD

**Issue by gmulhearn** [hyperledger/aries-vcx#814]
# Context
In `aries_vcx_core/src/wallet/base_wallet.rs` a trait `BaseWallet` is defined. When `BaseWallet` was originally defined, it kept the implementation 'simple' by taking and returning structures in the form of JSON Strings rather than typed rust `struct`s. Now that `BaseWallet` is well integrated, we should go back and properly add types to the `BaseWallet` interface.

# Requirements
* All JSON strings inputs and return types in `BaseWallet` should be replaced with rust structs.
* implementations of `BaseWallet` (currently mostly just `IndySdkWallet`) should be updated to use the new types and translate them appropriately
* consumers of `BaseWallet` in the code base should be updated to use the new types rather than the JSON strings

# Examples:
## Example 1:
take this method;
```
    async fn add_wallet_record(&self, xtype: &str, id: &str, value: &str, tags_json: Option<&str>)
        -> VcxCoreResult<()>;
```

`tags_json` is an optional JSON string that represents a `HashMap<String, String>`.

so the method should be updated as:
```
    async fn add_wallet_record(&self, xtype: &str, id: &str, value: &str, tags: Option<HashMap<String,String>>)
        -> VcxCoreResult<()>;
```

## Example 2
```
    async fn get_wallet_record(&self, xtype: &str, id: &str, options_json: &str) -> VcxCoreResult<String>;
```

This method takes a JSON string via `options_json` and returns a JSON string that represents a "wallet record"

they should both be replaced with struct types.

If we drill into the `libvdrtools` implementation of `get_record` (drilled into via the IndySdkWallet::get_wallet_record implementation), we get a clue for what these structures would look like:
```
    /// options_json: //TODO: FIXME: Think about replacing by bitmask
    ///  {
    ///    retrieveType: (optional, false by default) Retrieve record type,
    ///    retrieveValue: (optional, true by default) Retrieve record value,
    ///    retrieveTags: (optional, false by default) Retrieve record tags
    ///  }
    /// #Returns
    /// wallet record json:
    /// {
    ///   id: "Some id",
    ///   type: "Some type", // present only if retrieveType set to true
    ///   value: "Some value", // present only if retrieveValue set to true
    ///   tags: <tags json>, // present only if retrieveTags set to true
    /// }
```

# Tips
Since `IndySdkWallet` is the primary implementation of `BaseWallet` currently, it's easiest to drill into the libvdrtools implementations for information about what the underlying JSON type should be.

**Comment by Patrik-Stas** [comment]
Hi @tech-bash, you are assigned. Apparently being member of organization is not requirement, but a person have to interact with the repo in certain way (star the repo / submit PR / etc.)

@tech-bash before you dive in, please wait for this https://github.com/hyperledger/aries-vcx/issues/815#issuecomment-1526188915 to be clarified.

**Comment by tech-bash** [comment]
Alright.

**Comment by gmulhearn** [comment]
@tech-bash this issue is not blocked by the other issue. For this issue you should go ahead with implementing your own types as structs where required (nothing has changed from the issue description above)

**Comment by tech-bash** [comment]
OK

**Comment by tech-bash** [comment]
@gmulhearn in example 1 that you gave I guess there is nothing new in the updated expression ;), also just to make sure if we would write `serde::json::from_str(&tags_json):  Options<&str>`, would this be valid in our case? Coz I suppose we only need to deserialize the json data for conversion into a rust struct!

**Comment by gmulhearn** [comment]
Whoops. I have fixed the example 1, thanks for mentioning

**Comment by tech-bash** [comment]
Alright, got you!

**Comment by gmulhearn** [comment]
Reopening, as #843 does not completely solve this issue. Still remaining is the typed struct for a `WalletRecord` item

**Comment by Patrik-Stas** [comment]
Done in 
https://github.com/hyperledger/aries-vcx/pull/1085
https://github.com/hyperledger/aries-vcx/pull/1084
