### ISSUE TITLE
Move MaybeKnown enum to shared_vcx

### ISSUE THREAD

**Issue by bobozaur** [hyperledger/aries-vcx#839]
The `MaybeKnown<T>` enum is used for deserializing a type which could also deserialize to `String`, essentially trying the `Known<T>` variant first with the specified type (generally some other enum `T`) and falling back to the `Unknown(String)` variant if the first one fails.

This is right now declared in the `messages` crate as that's where it is mainly used, but does not really belong there as it fits a more general purpose, hence should be moved to the `shared_vcx` crate.

Moreover, the type could be extended to fit some other use cases by using a second generic as `Unknown(U)` (which could very well default to `String` as that's the most common use case).

Steps:
    - [ ] Move `MaybeKnown<T>` to `shared_vcx`.
    - [ ] To make it more extensible, add a second generic to the type which defaults to `String` (as that's the most common use case and this way existing code wouldn't break).

**Comment by nachiketkanore** [comment]
I would like to work on this!
