### ISSUE TITLE
Typing of JSON strings on Prover handler APIs

### ISSUE THREAD

**Issue by gmulhearn** [hyperledger/aries-vcx#847]
There are a few APIs in the aries_vcx Prover implementation which use complicated JSON for API inputs & outputs. These should ideally be replaced with typed structs.

# retrieve_credentials
```rust
pub async fn retrieve_credentials(&self, profile: &Arc<dyn Profile>) -> VcxResult<String>
```
where the return JSON String should be replaced with some `RetrievedCredentials` struct.

looking at the internals of an implementation (specifically in `prover.rs` `fetch_credential`), we can see the intended structure:
```json
{
  "attrs": {
    "<referent (pred or attr referent)>": [{
      "cred_info": {
        "referent": "<credential identifier>",
        "attrs": { "<attr_name>": "<attr_raw_value>", ... },
        "schema_id": "...",
        "cred_def_id": "...",
        "rev_reg_id"?: "..."?,
        "cred_rev_id"?: "..."?,
      },
      "non_revoc_interval": { "from"?: int?, "to"?: int? },
    }],
  }
}
```

# generate_presentation
```rust
pub async fn generate_presentation(
        &mut self,
        profile: &Arc<dyn Profile>,
        credentials: String,
        self_attested_attrs: String,
    ) -> VcxResult<()>
```

where `credentials` should be replaced with some `SelectedCredentials` struct. and `self_attested_attrs` should be replaced with `HashMap<String, String>`.

looking at the internals of aries_vcx (specifically in `prover_internal.rs` `fn credential_def_identifiers`), we can see the intended structure of `credentials`:

```json
{
  "attrs": {
    "<referent (pred or attr referent)>": {
      "credential": {
        "cred_info": {
          "referent": "<credential identifier>",
          "schema_id": "...",
          "cred_def_id": "...",
          "rev_reg_id"?: "..."?,
          "cred_rev_id"?: "..."?,
          "revealed"?: boolean?
        }
      },
      "tails_file": "<path to tails dir>"
    }
  }
}
```

Both of these changes could be made in a non-breaking manner for libvcx consumers by if libvcx continues to take/return JSON strings, but serializes/deserializes them before passing them to aries_vcx. 

It would be a breaking change for the aries_vcx APIs though. Which I think is for the best, as IMO, aries_vcx should be embracing all the Rust type-safety-goodness that it can 🚀.

# Open questions?
1. It seems to me that perhaps these are legacy structures, and for convenience, the structure for `RetrievedCredentials` and `SelectedCredentials` are pretty much identical. I'm guessing this is such that a consumer can just slightly manipulate the `RetrievedCredentials` JSON to "select a credential for each referent" and then pass it back as a `SelectedCredentials` JSON... So we could keep with this intention by having shared components of the data structures for both of them, or we could embrace that they are for different purposes and should be different types.
2. I do have some issues with these structures, for both, it seems odd that everything is nested in the `attrs` field (especially since `attrs` contains referents for attributes AND predicates). I've seen other aries APIs separate by attribute&predicate: `requested_attributes` & `requested_predicates` (similar to the proof request structure). Since we group everything under `attrs`, it leads to some smells, such as the consumer being able to put a `"revealed"` field under a selected cred_info for a predicate (which doesn't make sense, `revealed` is only for attribute-referents).
3. More on above ^, changing this would mean: there would be breaking changes for libvcx consumers.. so maybe not appropriate for right now.

**Comment by Patrik-Stas** [comment]
Agree on `1`, and I suppose `2` will naturally emerge as need in process of implementing the `1`.

As for `3`, we could rename existing apis to `legacy_*` and implement `retrieve_credentials` & `generate_presentation` in typed manner, even with changes in terms of different data structures. We could keep `legacy_*` for one or two releases, then drop them.

**Comment by gmulhearn** [comment]
Fixed with referenced PR ^
